### ISSUE TITLE
mapView:didTapAtCoordinate: in MapDirections project not firing

### ISSUE THREAD

**Issue by tlenton** [ManoMarks/demos#2]
In the MapDirections project the demo wasn't working for me because the mapView:didTapAtCoordinate: delegate method in MDViewController was not firing.

To fix this I had to add the <GMSMapViewDelegate> protocol to the interface definition in MDViewController.h 

This also fixed a warning that was caused by assigning the mapView_.delegate to self in loadView.

Version details: Xcode 5.0.2, deployment target 6.0, and running on iPad Simulator with iOS 6.1 & 7

**Comment by mikewitney** [comment]
Hello, 

What do you think about  that ornaments? Please  take a look and tell me whether you  like them, here is the link <http://invitation.thepachinko.com/aeiwbv>

Later, mike
